AWS_ACCESS_KEY_ID = 'AWS_KEY_HERE'
AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY_HERE'
BROKER_TRANSPORT = 'sqs'
BROKER_TRANSPORT_OPTIONS = {
    'region': 'us-east-1',
}
BROKER_USER = AWS_ACCESS_KEY_ID
BROKER_PASSWORD = AWS_SECRET_ACCESS_KEY
